Activity log
aerogear/unifiedpush-admin-ui pull request #77
Opened 2020-08-12 19:57 UTC by secondsun

Requires https://github.com/aerogear/unifiedpush-admin-client/pull/114

![Screenshot from 2020-08-12 15-56-40](https://user-images.githubusercontent.com/2413816/90061662-7007ba00-dcb4-11ea-93eb-e88d4d33cd35.png)

2020-08-19 01:26 UTC, secondsun commented
@ziccardi Can you take a look?

2020-08-19 13:13 UTC, ziccardi requested changes

2020-08-19 13:13 UTC, ziccardi commented on src/styles/App.scss
> +@import 'activity-list.scss';
This file does not exists in this PR

2020-08-19 13:13 UTC, ziccardi commented on src/application/ApplicationDetail/panels/ActivityLogPanel.tsx
> +            variant="warning"
I believe this should be an inline alert (add `isInline`: https://www.patternfly.org/v4/documentation/react/components/alert#inline-types)

2020-08-31 13:45 UTC, ziccardi approved these changes

2020-08-31 13:47 UTC, merged