Pf4 rebased
aerogear/unifiedpush-admin-ui pull request #94
Opened 2020-09-16 20:11 UTC by secondsun

## Motivation
This is THE Patternfly 4 rewrite PR, plus a couple of small bug fixes rebased on master.

Good luck.

2020-09-16 20:28 UTC, secondsun commented
@ziccardi I propose we allow the merge even with the commit lint failures. This is a PR for you to check, I found a couple of problems with the sender UI that I fixed, as well as a rebase on master. Ideally nothing is more broken than it was before I rebased.

2020-09-17 14:13 UTC, ziccardi requested changes

2020-09-17 14:13 UTC, ziccardi commented on src/application/crud/DeleteApplicationPage.tsx
> +      <Modal
I\d change this to a simple:
```typescript
if (!this.props.app) {
   return <></>;
}
return ( <Modal
    ...
```

2020-09-17 14:13 UTC, ziccardi commented on src/application/crud/DeleteVariantPage.tsx
> +        // this.props.app.variants = this.props.app!.variants!.filter(filteredVar => filteredVar.variantID !== variant.variantID);
delete

2020-09-17 14:13 UTC, ziccardi commented on src/application/crud/DeleteVariantPage.tsx
> +      console.log(err);
replace with `(this.context as ContextInterface).alert(err);`

2020-09-17 14:13 UTC, ziccardi commented on src/application/crud/RenameVariantPage.tsx
> +      console.log(err);
Replace with `(this.context as ContextInterface).alert(err);`

2020-09-17 14:13 UTC, ziccardi commented on src/application/wizard/SendTestNotificationPage.tsx
> +        defaultValue={`Hello! This is my first notification to ${props.variant.name}`}
```suggestion
        defaultValue={testMessage}
```

2020-09-17 14:13 UTC, ziccardi commented on startup.sh
> +nginx -g "daemon off;"
this is both here and in the docker file as a CMD.
Let's take just one

2020-09-17 14:23 UTC, secondsun commented on src/application/ApplicationDetail/panels/ActivityLogPanel.tsx
> +                this.loadActivityLog(currentPage - 1)
The loadActivityLog is 0 indexed, but the pager is 1 indexed

2020-09-17 16:12 UTC, ziccardi approved these changes
Agree with overriding commitlint for this PR.
👍

2020-09-17 16:13 UTC, merged